# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest    
    defaults:
       run:
         shell: bash
         working-directory: ${{ github.workspace }}

    steps:    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Checkout Lyt.Avalonia.Framework
      uses: actions/checkout@v4
      with:
        repository: LaurentInSeattle/Lyt.Avalonia.Framework
        ref: master
        path: sauce\Lyt.Avalonia.Framework
         
    - name: Restore dependencies
      run: dotnet restore
      working-directory: sauce\Lyt.Avalonia.Framework

    - name: Build
      run: dotnet build --no-restore
      working-directory: sauce\Lyt.Avalonia.Framework
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: sauce\Lyt.Avalonia.Framework
